version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      - TZ="America/Chicago"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - transmission
      - verse-extra
      - calibre

networks:
  transmission:
    external: true
    name: transmission
  verse-extra:
    external: true
    name: verse-extra
  calibre:
    external: true
    name: calibre
